//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modbus {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Modbus.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Specialized use in conjunction with programming commands. The server (or slave) has accepted the request and is processing it, but a long duration of time will be required to do so. This response is returned to prevent a timeout error from occurring in the client (or master). The client (or master) can next issue a Poll Program Complete message to determine if processing is completed..
        /// </summary>
        internal static string Acknowlege {
            get {
                return ResourceManager.GetString("Acknowlege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Argument endPoint cannot be empty..
        /// </summary>
        internal static string EmptyEndPoint {
            get {
                return ResourceManager.GetString("EmptyEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Specialized use in conjunction with gateways, indicates that the gateway was unable to allocate an internal communication path from the input port to the output port for processing the request. Usually means that the gateway is misconfigured or overloaded..
        /// </summary>
        internal static string GatewayPathUnavailable {
            get {
                return ResourceManager.GetString("GatewayPathUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Specialized use in conjunction with gateways, indicates that no response was obtained from the target device. Usually means that the device is not present on the network..
        /// </summary>
        internal static string GatewayTargetDeviceFailedToRespond {
            get {
                return ResourceManager.GetString("GatewayTargetDeviceFailedToRespond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hex string must have even number of characters..
        /// </summary>
        internal static string HexCharacterCountNotEven {
            get {
                return ResourceManager.GetString("HexCharacterCountNotEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The data address received in the query is not an allowable address for the server (or slave). More specifically, the combination of reference number and transfer length is invalid. For a controller with 100 registers, the PDU addresses the first register as 0, and the last one as 99. If a request is submitted with a starting register address of 96 and a quantity of registers of 4, then this request will successfully operate (address-wise at least) on registers 96, 97, 98, 99. If a request is submitted with  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string IllegalDataAddress {
            get {
                return ResourceManager.GetString("IllegalDataAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A value contained in the query data field is not an allowable value for server (or slave). This indicates a fault in the structure of the remainder of a complex request, such as that the implied length is incorrect. It specifically does NOT mean that a data item submitted for storage in a register has a value outside the expectation of the application program, since the MODBUS protocol is unaware of the significance of any particular value of any particular register..
        /// </summary>
        internal static string IllegalDataValue {
            get {
                return ResourceManager.GetString("IllegalDataValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The function code received in the query is not an allowable action for the server (or slave). This may be because the function code is only applicable to newer devices, and was not implemented in the unit selected. It could also indicate that the server (or slave) is in the wrong state to process a request of this type, for example because it is unconfigured and is being asked to return register values..
        /// </summary>
        internal static string IllegalFunction {
            get {
                return ResourceManager.GetString("IllegalFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Specialized use in conjunction with function codes 20 and 21 and reference type 6, to indicate that the extended file area failed to pass a consistency check..
        /// </summary>
        internal static string MemoryParityError {
            get {
                return ResourceManager.GetString("MemoryParityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Array networkBytes must contain an even number of bytes..
        /// </summary>
        internal static string NetworkBytesNotEven {
            get {
                return ResourceManager.GetString("NetworkBytesNotEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Specialized use in conjunction with programming commands. The server (or slave) is engaged in processing a long–duration program command. The client (or master) should retransmit the message later when the server (or slave) is free..
        /// </summary>
        internal static string SlaveDeviceBusy {
            get {
                return ResourceManager.GetString("SlaveDeviceBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unrecoverable error occurred while the server (or slave) was attempting to perform the requested action..
        /// </summary>
        internal static string SlaveDeviceFailure {
            get {
                return ResourceManager.GetString("SlaveDeviceFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Function Code: {1}{0}Exception Code: {2} - {3}.
        /// </summary>
        internal static string SlaveExceptionResponseFormat {
            get {
                return ResourceManager.GetString("SlaveExceptionResponseFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid function code value for SlaveExceptionResponse..
        /// </summary>
        internal static string SlaveExceptionResponseInvalidFunctionCode {
            get {
                return ResourceManager.GetString("SlaveExceptionResponseInvalidFunctionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UdpClient must be bound to a default remote host. Call the Connect method..
        /// </summary>
        internal static string UdpClientNotConnected {
            get {
                return ResourceManager.GetString("UdpClientNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown slave exception code..
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WaitToRetryMilliseconds must be greater than 0..
        /// </summary>
        internal static string WaitRetryGreaterThanZero {
            get {
                return ResourceManager.GetString("WaitRetryGreaterThanZero", resourceCulture);
            }
        }
    }
}
